name: Builds

on:
  push:
    paths-ignore:
      - 'Source/Docs/**'
  pull_request:
    paths-ignore:
      - 'Source/Docs/**'

permissions:
  contents: write

env:
  BUILD_VERSION: 2.6.0.${{ github.run_number }}

jobs:

  macos-build:
    name: MacOS Build
    runs-on: macos-latest
    timeout-minutes: 15
    steps:
      - name: Set net8.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
      - name: View Build Version
        run: echo ${{ env.BUILD_VERSION }}
      - name: View Github Info
        run: echo repository=${{ github.repository }} event_name=${{ github.event_name }} ref=${{ github.ref }} head_ref=${{ github.head_ref }} base_ref=${{ github.base_ref }}
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Restore nuget Packages
        run: dotnet restore Source/Mosa.Linux.sln
      - name: Build
        run: dotnet build Source/Mosa.Linux.sln
      - name: Unit Test
        run: dotnet test Source/Mosa.Linux.sln
      - name: Store Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: macos-build-artifact
          path: bin

  macos-unit-testing:
    strategy:
      fail-fast: false
    name: MacOS - Unit Test -o0
    runs-on: macos-latest
    timeout-minutes: 15
    needs: macos-build
    steps:
      - name: Set net8.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Download Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: macos-build-artifact
          path: bin
      - name: Install Qemu
        run: brew install qemu
      - name: Create Temp Directory
        run: mkdir bin/BinTempARM0
      - name: Unit Test 
        run: dotnet bin/Mosa.Utility.UnitTests.dll -check -o0 -o bin/BinTempARM0/UnitTests.bin
      - name: Upload Binary Files
        uses: actions/upload-artifact@master
        with:
          name: BinTemp
          path: bin/BinTempARM0
        if: always()

  macos-demo-testing:
    strategy:
      fail-fast: false
    name: MacOS - Demo Test -o0
    runs-on: macos-latest
    timeout-minutes: 15
    needs: macos-build
    steps:
      - name: Set net8.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Download Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: macos-build-artifact
          path: bin
      - name: Install Qemu
        run: brew install qemu
      - name: Demo Test - BareMetal Starter
        run: dotnet bin/Mosa.Tool.Launcher.Console.dll bin/Mosa.BareMetal.Starter.x86.dll -o0 -check -test -output-counters
      - name: Demo Test - BareMetal TestWorld
        run: dotnet bin/Mosa.Tool.Launcher.Console.dll bin/Mosa.BareMetal.TestWorld.x86.dll -o0 -check -test -output-counters
      - name: Demo Test - BareMetal HelloWorld
        run: dotnet bin/Mosa.Tool.Launcher.Console.dll bin/Mosa.BareMetal.HelloWorld.x86.dll -o0 -check -test -output-counters
      - name: Demo Test - BareMetal CoolWorld
        run: dotnet bin/Mosa.Tool.Launcher.Console.dll bin/Mosa.BareMetal.CoolWorld.x86.dll -o0 -check -test -vmware-svga -include bin/Include
